services:
  openmanus:
    image: ghcr.io/coppolekkia/manus:latest
    container_name: openmanus_agent
    stdin_open: true
    tty: true
    volumes:
      # Peschiamo il file dal nuovo percorso
      - /var/lib/manus_config:/app/config
    restart: unless-stopped
